apiVersion: v1
kind: Service
metadata:
  name: webapi-service
  labels:
    name: webapi-service
    app: webapi
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30001
  selector:
    name: webapi-pod
    app: webapi